---
volumes:
  data:
services:
  oxidized:
    restart: always
    build: ./app
    container_name: oxidized
    volumes:
      - data:/home/oxidized/.config/oxidized
    ports:
      - 8888:8888/tcp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 5s
