---
services:
  oxidized:
    restart: always
    image: docker.io/oxidized/oxidized:${oxidized_version}
    ports:
      - 8888:8888/tcp
    environment:
      # Reload hosts list once per day
      CONFIG_RELOAD_INTERVAL: 86400
    volumes:
       - .config/oxidized:/home/oxidized/.config/oxidized/
